common_params = {'etoh_distribution_truck': {'low' : 45, 
				                             'avg' : 50, 
				                             'high' : 55}, 
				'etoh_distribution_rail': {'low': 120, 
				                           'avg': 135, 
				                           'high': 150}, 
				'enzyme': {'low': 0.027, 
				          'avg': 0.03, 
				          'high': 0.033}}


other_params = {"iHG-Projected": {'chlys_amount': {'low': 0.027, 
					                               'avg': 0.03,  
					                               'high': 0.033},
					              'electricity_requirements': {'low': 0, 
								                               'avg': 0,  
								                               'high': 0},
					              'feedstock': {'low': 4.23, 
				                                'avg': 4.7,  
				                                'high': 5.17},
				                  'electricity_credit': {'low': 0, 
						                                 'avg': 0,  
						                                 'high': 0}},
				"iHG-Current": {'chlys_amount': {'low': 0.14, 
					                             'avg': 0.16,  
					                             'high': 0.18},
					            'electricity_requirements': {'low': 0, 
								                             'avg': 0,  
								                             'high': 0},
					            'feedstock': {'low': 4.23, 
				                                'avg': 4.7,  
				                                'high': 5.17},
				                'acid': {'low': 0.16, 
				                         'avg': 0.18,  
				                         'high': 0.2},
				                'electricity_credit': {'low': 0.9, 
						                                'avg': 0.85,  
						                                'high': 0.8}},
				"waterwash": {'chlys_amount': {'low': 0.15, 
					                            'avg': 0.17,  
					                            'high': 0.18},
					          'electricity_requirements': {'low': 1.26, 
								                           'avg': 1.4,  
								                           'high': 1.54},
					          'feedstock': {'low': 4.9, 
				                             'avg': 5.47,  
				                             'high': 6.01},
				              'ng_input_stream_mass_ww_kg': {'low': 1.1, 
									                         'avg': 1.31,  
									                         'high': 1.4},
							  'electricity_credit': {'low': 0, 
					                                 'avg': 0,  
					                                 'high': 0}}}


