common_params = {'etoh_distribution_truck': {'low' : 45, 
				                             'avg' : 50, 
				                             'high' : 55}, 
				'etoh_distribution_rail': {'low': 120, 
				                           'avg': 135, 
				                           'high': 150}, 
				'enzyme': {'low': 0.027, 
				           'avg': 0.03, 
				           'high': 0.033},
				'chlys_percent': {'low': 0.58, 
                                  'avg': 0.58,  
                                  'high': 0.58},
                'cholinium_percent': {'low': 0.42, 
	                                  'avg': 0.42,  
	                                  'high': 0.42},
	            'chlys_rail_mt_km': {'low': 160, 
	                                 'avg': 160,  
	                                 'high': 160},
                'chlys_flatbedtruck_mt_km': {'low': 80, 
		                                     'avg': 80,  
		                                     'high': 80}}


other_params = {"iHG-Projected": {'chlys_amount': {'low': 0.027, 
					                               'avg': 0.03,  
					                               'high': 0.033},
					              'electricity_requirements': {'low': 0, 
								                               'avg': 0,  
								                               'high': 0},
					              'feedstock': {'low': 4.23, 
			                                    'avg': 4.7,  
			                                    'high': 5.17},
				                  'electricity_credit': {'low': 0, 
						                                 'avg': 0,  
						                                 'high': 0},
						          'csl.kg': {'low': 0.06, 
			                                 'avg': 0.06,  
			                                 'high': 0.06},
					              'dap.kg': {'low': 0.017, 
			                                 'avg': 0.017,  
			                                 'high': 0.017},
			                      'h2so4.kg': {'low': 0, 
			                               	   'avg': 0,  
			                              	   'high': 0},
			                      'hcl.kg': {'low': 0, 
			                                 'avg': 0,  
			                                 'high': 0},
				                  'electricity_credit': {'low': 0, 
						                                 'avg': 0,  
						                                 'high': 0},
						          'ng_input_stream_mass_ww_kg': {'low': 0, 
										                         'avg': 0,  
										                         'high': 0}},
				"iHG-Current": {'chlys_amount': {'low': 0.14, 
					                             'avg': 0.16,  
					                             'high': 0.18},
					            'electricity_requirements': {'low': 0, 
								                             'avg': 0,  
								                             'high': 0},
					            'feedstock': {'low': 4.23, 
		                                      'avg': 4.7,  
		                                      'high': 5.17},
				                'acid': {'low': 0.16, 
				                         'avg': 0.18,  
				                         'high': 0.2},
				                'electricity_credit': {'low': 0.9, 
						                                'avg': 0.85,  
						                                'high': 0.8},
						        'csl.kg': {'low': 0.05, 
		                                 'avg': 0.05,  
		                                 'high': 0.05},
		                        'dap.kg': {'low': 0.01, 
		                                 'avg': 0.01,  
		                                 'high': 0.01},
					            'hcl.kg': {'low': 0.18, 
			                               'avg': 0.18,  
			                               'high': 0.18},
			                    'h2so4.kg': {'low': 0, 
			                               	 'avg': 0,  
			                              	 'high': 0},
		                        'ng_input_stream_mass_ww_kg': {'low': 0, 
										                       'avg': 0,  
										                       'high': 0}},
				"waterwash": {'chlys_amount': {'low': 0.15, 
					                            'avg': 0.17,  
					                            'high': 0.18},
					          'electricity_requirements': {'low': 1.26, 
								                           'avg': 1.4,  
								                           'high': 1.54},
					          'feedstock': {'low': 4.9, 
		                                    'avg': 5.47,  
		                                    'high': 6.01},
				              'ng_input_stream_mass_ww_kg': {'low': 1.1, 
									                         'avg': 1.31,  
									                         'high': 1.4},
							  'electricity_credit': {'low': 0, 
					                                 'avg': 0,  
					                                 'high': 0},
					          'csl.kg': {'low': 0.06, 
		                                 'avg': 0.06,  
		                                 'high': 0.06},
				              'dap.kg': {'low': 0.01, 
		                                 'avg': 0.01,  
		                                 'high': 0.01},
		                      'hcl.kg': {'low': 0, 
			                               'avg': 0,  
			                               'high': 0},
				              'h2so4.kg': {'low': 0.002, 
			                               'avg': 0.002,  
			                               'high': 0.002},
			                  'electricity_credit': {'low': 0, 
					                                 'avg': 0,  
					                                 'high': 0}}}


all_params_list = ['lysine.us.kg', 'cholinium.hydroxide.kg', 'cellulase.kg']


